# Generated by Django 5.2.7 on 2025-10-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="state",
            field=models.CharField(
                choices=[
                    ("DRAFT", "draft"),
                    ("SENDING", "sending"),
                    ("SENT", "sent"),
                    ("RECEIVED", "received"),
                    ("READ", "read"),
                    ("ERROR", "error"),
                    ("CANCELLED", "cancelled"),
                    ("RETRY", "retry"),
                    ("DELETED", "deleted"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=10,
            ),
        ),
    ]
