# Generated by Django 5.2.7 on 2025-10-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_message_state"),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='target',
        ),
    ]
