# Generated by Django 5.2.7 on 2025-10-15 20:27

import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_message_author_alter_message_target"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"get_latest_by": "modified"},
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="message",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="message",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="conversation",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="conversation",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="message",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
    ]
