# Generated by Django 5.2.7 on 2025-10-16 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_alter_conversation_options_alter_message_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="target",
        ),
    ]
