# Generated by Django 5.2.7 on 2025-10-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_remove_message_target"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["created"],
                "verbose_name": "message",
                "verbose_name_plural": "messages",
            },
        ),
        migrations.AlterField(
            model_name="message",
            name="state",
            field=models.CharField(
                choices=[
                    ("DRAFT", "draft"),
                    ("SENT", "sent"),
                    ("ERROR", "error"),
                    ("CANCELLED", "cancelled"),
                    ("RETRY", "retry"),
                    ("DELETED", "deleted"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=10,
            ),
        ),
    ]
